version: "3.1"
  
services:
  # Servicio Apache 1
  apache1:
    image: httpd:2.4
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/ # Monta el archivo index.html local en el directorio del contenedor
    ports:
      - "8083:80" # Mapea el puerto 8083 del host al puerto 80 del contenedor

  # Servicio Nginx
  nginx:
    image: nginx
    restart: always # Reinicia siempre el contenedor en caso de fallo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Monta el archivo default.conf local en el directorio de configuración del contenedor
    ports:
      - "8081:80" # Mapea el puerto 80 del host al puerto 80 del contenedor
      #Indica que el servicio depende de la disponibilidad de los 3 apache
    
  GotaMeteor_api:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8085:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=Eneko
      - DB_PASSWORD=12345678
      - DB_DATABASE=Eneko
    volumes:
      - './datos_proyecto/GotaMeteor_api/:/app'
    command: ["sh", "-c", "php artisan migrate && php artisan passport:install --force && php artisan serve --host=0.0.0.0"]
    depends_on:
             mysql:
                condition: service_healthy

  GotaMeteor_tratamiento_datos:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8086:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=Eneko
      - DB_PASSWORD=12345678
      - DB_DATABASE=Eneko
    volumes:
      - './datos_proyecto/GotaMeteor_datos/:/app'
    command: ["php", "artisan", "schedule:work"]
    depends_on:
             mysql:
                condition: service_healthy

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'Eneko'
      MYSQL_USER: 'Eneko'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './datos_proyecto/mysql/:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  phpmyadmin:
    image: 'phpmyadmin:latest'
    ports:
      - 8084:80
    environment:
      - PMA_ARBITRARY=1